#Day-1 Assignment

#Question no:1

#Customer Bank Details
#Name=input('Enter your name :')
#Age=int(input("Enter your Age :"))
#Account_Number = int(input("Enter your account number :"))
#Address = input("Enter your Address :")
#print = ("Enter your Name :",Name)
#print = ("Enter your Age :", Age)
#print = ("Enter your acc_Number :", Number)
#print = ("Enter your Address :", Address)





#Question no:2

#average and sum of five subjects

print("Enter marks of five subject:")

sub1= int(input("Enter your mark of html :"))
sub2= int(input("Enter your mark of css :"))
sub3= int(input("Enter your mark of js :"))
sub4= int(input("Enter your mark of react :"))
sub5= int(input("Enter your mark of Sql :"))

Total =sub1 + sub2 + sub3+ sub4 + sub5

average = total/5

print=("Total Marks =", total)
print=("average marks =", average)
